<h3>Contacts</h3>
<form action="" method="POST">
    <input type="text" class="form-control" name="name" placeholder="Your Name"><br>
    <input type="text" class="form-control" name="email" placeholder="Your Email"><br>
    <textarea name="message" class="form-control" placeholder="Your message"></textarea><br>
    <button class="btn btn-lg bg-primary btn-block" type="submit">Send</button>
</form>